AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - spec/dummy/**/*



# Metrics
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - '*.gemspec'
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*


# Style
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
