AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - .circleci/*
    - bin/*
    - coverage/**/*
    - spec/dummy/**/*
    - vendor/**/*



# Metrics
Metrics/AbcSize:
  Max: 16
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - '*.gemspec'
Metrics/CyclomaticComplexity:
  Max: 10
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 16
  Exclude:
    - db/migrate/**/*


# Style
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
