default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 8 } %>

development:
  <<: *default
  database: rapils_development

test:
  <<: *default
  database: rapils_test
